language: php

php:
  - 7.3

node_js:
  - 10

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - npm install
  - npm run production
  - vendor/bin/jigsaw build production

deploy:
  local_dir: build_production
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master

notifications:
  email:
    recipients:
      - bliz48rus@gmail.com
    on_success: never
    on_failure: always
